.travis.yml
Closes https://github.com/coala/corobo/issues/49
=> .travis.yml: Change to stable coala from rc2

.travis.yml
Closes https://github.com/coala/corobo/issues/63
=> .travis.yml: Uninstall vim-vint

.travis.yml
Closes https://github.com/coala/corobo/issues/65
=>  .travis.yml: Remove the vim-vint install statement

plugins/nevermind.py
Fixes https://github.com/coala/corobo/issues/73
=> nevermind.py: Add doc string for nm command

.github/PULL_REQUEST_TEMPLATE
Closes https://github.com/coala/corobo/issues/78
=>  .github: Add PR template

.coafile, config.py, plugins/ghetto.py, plugins/nevermind.py
Closes https://github.com/coala/corobo/issues/87
=> .coafile: Change prefered quotation to ' and apply

.travis.yml
Closes https://github.com/coala/corobo/issues/91
=> .travis.yml: Show missing column in tests

test-requirements.txt, tests/cassettes/ghetto.yaml, tests/ghetto_test.py
Closes https://github.com/coala/corobo/issues/95
=> ghetto: Record the test request and use it

plugins/labhub.plug, plugins/labhub.py
=> labhub: Add base plugin

.travis.yml
=> .travis.yml: Add integration for gitter chatroom

plugins/explain.plug, plugins/explain.py, tests/explain_test.py
Closes https://github.com/coala/corobo/issues/7
=> gsoc: explain: Add explain plugin

plugins/lmgtfy.plug, plugins/lmgtfy.py, tests/lmgtfy_test.py
I have to escape the square brackets otherwise it is not transmitted well, and we won't get a markdown link in the chat. See https://github.com/errbotio/errbot/issues/1018
=> lmgtfy: Add lmgtfy plugin[gsoc]

.coafile, plugins/ship_it.plug, plugins/ship_it.py, tests/ship_it_test.py
Closes https://github.com/coala/corobo/issues/14
=> ship_it: Add ship_it plugin [gsoc]

.travis.yml, setup.cfg
Closes https://github.com/coala/corobo/issues/106
=> setup.cfg: Add pytest opts

.travis.yml
=> .travis.yml: Run tests in docker

setup.cfg
Closes https://github.com/coala/corobo/issues/115
=> gsoc: setup.cfg: Move the tests to testpaths key

plugins/constants.py, plugins/searchdocs.plug, plugins/searchdocs.py, tests/searchdocs_test.py
Closes https://github.com/coala/corobo/issues/15
=> gsoc: searchdocs: Add searchdocs plugin

plugins/wolfram_alpha.plug, plugins/wolfram_alpha.py, requirements.txt, tests/cassettes/wa.yaml, tests/wolfram_alpha_test.py
Closes https://github.com/coala/corobo/issues/5
=> gsoc: wolframalpha: Add wolframalpha plugin

config.py
=> config.py: Set bot prefix to corobo

plugins/labhub.py
Fixes https://github.com/coala/corobo/issues/132
=> labhub: Pass the token as kwarg token

plugins/coala_lowercase_c.plug, plugins/coala_lowercase_c.py, tests/coala_lowercase_c_test.py
Closes https://github.com/coala/corobo/issues/129
=> coala_lowercase_c: Add coala_lowercase_c plugin

Dockerfile, config.py, requirements.txt, utils/utils.plug, utils/utils.py
=> utils: utilities for managing errbot

utils/utils.py
=> utils: Fix the AttributeError

webservices.raml
Closes https://github.com/coala/corobo/issues/123
=> webservices.raml.yaml: Add coala webservices raml

config.py
Adds to https://github.com/coala/corobo/issues/32
=> config.py: Divert help command to private message.

README.md
Closes https://github.com/coala/corobo/issues/125
=> README.md: Add Semaphore CI badge

plugins/coatils.plug, plugins/coatils.py, requirements.txt, tests/cassettes/coatils_all_langs.yaml, tests/cassettes/coatils_bear_stats.yaml, tests/cassettes/coatils_bear_stats_lang.yaml, tests/cassettes/coatils_contrib.yaml, tests/cassettes/coatils_lang_stats.yaml, tests/cassettes/coatils_stats.yaml, tests/cassettes/coatils_total_bears.yaml, tests/coatils_test.py
Closes https://github.com/coala/corobo/issues/18
=> [MERGE] coatils: Add contrib stats

config.py, plugins/labhub.py, requirements.txt, tests/labhub_test.py
=> requirements.txt: Bump IGitt version

README.md
=> README: Add information regarding env vars

plugins/ship_it.py, tests/ship_it_test.py
=> remove ship it emoticon

plugins/explain.py
Closes https://github.com/coala/corobo/issues/170
=> explain: Add promotion requirements

plugins/wolfram_alpha.py, tests/cassettes/wa.yaml, tests/wolfram_alpha_test.py
There are questions/strings that doesn't yield any pods at all, which raise
KeyError.
Fixes https://github.com/coala/corobo/issues/161
=> wolfram_alpha: Check if the pods exist

.ci/deploy.sh
This script is in charge of doing the actual deployment and it's
executed from the server.
Related to https://github.com/coala/corobo/issues/156
=> Add deployment script

config.py
Closes https://github.com/coala/corobo/issues/149
=> config.py: Add CHATROOM_PRESENCE

plugins/labhub.py
Closes https://github.com/coala/corobo/issues/147
=> labhub: Include link to gitter message in iss body

plugins/labhub.py
Currently, it just mentions username.
=> labhub: Use @-mention in issue body

plugins/coatils.py, tests/coatils_test.py
Closes https://github.com/coala/corobo/issues/16
=> coatils: Add ls bears cmd

.ci/deploy.sh
Closes https://github.com/coala/corobo/issues/185
=> deploy.sh: Show the command that is running

config.py
=> config: Fix the config file

README.md, plugins/constants.py
=> constants: Make org names configurable

plugins/labhub.py
Closes https://github.com/coala/corobo/issues/202
=> labhub: Add usability with sub-groups

plugins/explain.py, tests/explain_test.py, utils/filters.plug, utils/filters.py
Closes https://github.com/coala/corobo/issues/195
Closes https://github.com/coala/corobo/issues/194
=> filters: Filter echo cmd from coala and bears

plugins/explain.py
Closes https://github.com/coala/corobo/issues/164
=> explain: Change coala.io/git to coala.io/rebase

plugins/labhub.py, tests/labhub_test.py
=> labhub: Use @-mentions in create issue

plugins/labhub.py
Fixes https://github.com/coala/corobo/issues/208
=> labhub: Def team 'coala newcomers' -> 'newcomers'

README.md
=> README: Add docker setup instructions&improvements

plugins/coatils.py, tests/cassettes/coatils_run_coala.yaml, tests/coatils_test.py
Closes https://github.com/coala/corobo/issues/19
=> coatils: Add run coala cmd

plugins/coatils.py, tests/cassettes/coatils_run_coala.yaml, tests/coatils_test.py
=> coatils: Fix formatting in run command

README.md, config.py, utils/filters.py
=> utils/filters: Filter messages of ignored users

.coafile, answers/Dockerfile, answers/extraction.py, answers/final.py, answers/requirements.txt, answers/service.py, answers/utils.py, plugins/answer.plug, plugins/answer.py, tests/answer_test.py, tests/cassettes/answer.yaml
=> answers: Add answering plugin and infrastructure

plugins/labhub.py
Hey,
Let me know if anything else is required. 😄
=> labhub: Add invtation accept message

.ci/semaphore.docker.sh, .ci/semaphore.setup.sh, .ci/semaphore.tests.sh
Closes https://github.com/coala/corobo/issues/248
=> .ci/semaphore: Add setup, tests, docker steps

.ci/semaphore.docker.sh, README.md, answers/Dockerfile, answers/extraction.py, answers/final.py, answers/service.py
Closes https://github.com/coala/corobo/issues/236
=> answers: Remove singleton data holder DATA & adapt

.ci/semaphore.docker.sh, plugins/labhub.py
Closes https://github.com/coala/corobo/issues/246
=> labhub: Add newcomer form to developer welcome msg

answers/service.py, plugins/answer.py, tests/answer_test.py, tests/cassettes/answer.yaml
Fixes https://github.com/coala/corobo/issues/263
=> answers: POST text to summarize as data

answers/Dockerfile, answers/extraction.py, plugins/answer.py, tests/answer_test.py, tests/cassettes/answer.yaml
Closes https://github.com/coala/corobo/issues/260
=> gsoc: answers: Extract docs from coala/documentation

plugins/answer.py
=> plugins/answer.py: typo data -> json

plugins/answer.py, tests/answer_test.py
Closes https://github.com/coala/corobo/issues/265
=> plugins/answers: Return top 3 answers

docs/corobo.rst
=> docs/corobo.rst: Document corobo commands

docs/answers.rst
=> docs/answers.rst: Add docs regarding answers

.ci/check_docker.py, .ci/semaphore.answers.sh, .ci/semaphore.docker.sh, plugins/labhub.py, requirements.txt, tests/labhub_test.py
Closes https://github.com/coala/corobo/issues/224
=> stats: Add PR stats plugin

.ci/semaphore.answers.sh
Fixes https://github.com/coala/corobo/issues/281
=> semaphore.answers: Check only for non-master

README.md
Closes https://github.com/coala/corobo/issues/278
=>  README: Add gitter room badge linking to corobo channel

plugins/pitchfork.plug, plugins/pitchfork.py, tests/pitchfork_test.py
Closes https://github.com/coala/corobo/issues/36
=> pitchfork: Add pitchfork plugin

plugins/labhub.py
changed ourcommunity to our community
Closes #214
=> labhub: Add missing whitespace

plugins/ship_it.py
=> ship_it: Remove 404'ing images

config.py, utils/deprecate_cobot.plug, utils/deprecate_cobot.py
=> Deprecating cobot

README.md
Closes https://github.com/coala/corobo/issues/228
=> README.md: Add about section

plugins/labhub.py, plugins/ship_it.py, tests/labhub_test.py
Closes https://github.com/coala/corobo/issues/292
=> LabHub: Add invite me cmd

plugins/labhub.py, tests/labhub_test.py
=> labhub: merge invite me and invite_cmd function

plugins/labhub.py, tests/labhub_test.py
=> LabHub: Block gci issue assignments

utils/backends.py
=> utils/backends: Fix string formatting

.gitignore, README.md, config.py, data/.gitignore
=> Make the bot usable on startup without configuration

plugins/explain.py
Fix the alignment of review in ``explain.py``.
Closes https://github.com/coala/corobo/issues/379
=> explain.py: Fix review alignment

plugins/git_stats.py, tests/git_stats_test.py
git_stats.py: fixes AttributeError crash
Fixes https://github.com/coala/corobo/issues/438
=> git_stats.py: fixes AttributeError crash

README.md
Discards Travis Badge as it is not used here
Fixes https://github.com/coala/corobo/issues/487
=> README.md: Remove Travis Badge

config.py
Closes https://github.com/coala/corobo/issues/469
=> config: Disable all labhub commands in private

README.md, config.py
=> Gitter backend auto configuration

plugins/templates/labhub/errors/not-maintainer.jinja2.md
username-->target
Closes https://github.com/coala/corobo/issues/479
=> not-maintainer.jinja2.md: Replace a word

plugins/labhub.py
=> labhub.py: Add help message for pr_stats command

.coafile
Adds the additional issue-reference settings from
coala/coala-bears.
Closes https://github.com/coala/corobo/issues/422
=> .coafile: Enhance rules for commit

tests/labhub_test.py
Closes https://github.com/coala/corobo/issues/495
=> Fix create new issue test

.travis.yml
=> .travis.yml: Disables notifications on success

tests/labhub_test.py
Ignoring test for creating private issue
until a fix for the ACL failure has been
found.
Closes https://github.com/coala/corobo/issues/526
=> labhub_test: Ignore test temporarily

requirements.txt
Closes https://github.com/coala/corobo/issues/544
=> [GSoC '18]: requirements.txt: Bump IGitt version

plugins/labhub.py, plugins/templates/labhub/errors/not-eligible-invite.jinja2.md, plugins/templates/labhub/errors/not-maintainer.jinja2.md, tests/labhub_test.py
- Removed invite using `invite me`
- Developers have right to invite newcomers
- Invite only if invitee is a member of the room
Closes https://github.com/coala/corobo/issues/534
Closes https://github.com/coala/corobo/issues/535
cc @meetmangukiya @gbin @jayvdb
=> [GSoC '18] labhub: Modify invite permissions

plugins/constants.py, plugins/spam.plug, plugins/spam.py, plugins/templates/spam_alert.jinja2.md, tests/spam_test.py
Alert the user that they are spamming.
See: https://github.com/coala/corobo/issues/482 and https://gitlab.com/coala/cobot/issues/16
=> plugins: Add SpammingAlert plugin

plugins/labhub.py, plugins/templates/labhub/hello-world.jinja2.md, tests/labhub_test.py
Removal of automatic invitation of newcomers
through `Hello World` message in chat room.
Closes #538
=> [GSoC '18] labhub: Remove `Hello World` callback

tests/answer_test.py, tests/coatils_test.py, tests/wolfram_alpha_test.py
Closes https://github.com/coala/corobo/issues/529
=> Remove unnecessary self handling of TestBot

plugins/ban.plug, plugins/ban.py, tests/ban_test.py
Add command to ban a user from all
rooms at once.
Closes https://github.com/coala/corobo/issues/549
=> labhub: Add ban command

.gitignore
=> .gitignore: Add .pytest_cache

.coafile, tests/answer_test.py, tests/coala_lowercase_c_test.py, tests/coatils_test.py, tests/deprecate_bot_prefixes_test.py, tests/explain_test.py, tests/ghetto_test.py, tests/git_stats_test.py, tests/helper.py, tests/labhub_test.py, tests/lmgtfy_test.py, tests/nevermind_test.py, tests/pitchfork_test.py, tests/searchdocs_test.py, tests/ship_it_test.py, tests/the_rules_test.py
Closes https://github.com/coala/corobo/issues/565
=> .coafile: Include tests

plugins/labhub.py, tests/labhub_test.py
Make all LabHub commands accessible only by
members of the organization.
Closes https://github.com/coala/corobo/issues/548
=> Make Labhub commands accessible only to org members

.gitignore, test-requirements.txt
=> moban: Moban Sync

.moban.yaml, requirements.txt
Closes https://github.com/coala/corobo/issues/433
=> requirements: Unpin pyopenssl

answers/final.py
=> final.py: Remove unused imports  

config.py, data/.gitignore
Remove need for the empty `data/` subdirectory.
Closes https://github.com/coala/corobo/issues/569
=> config.py: Create empty data sub-directory

plugins/spam.py, tests/spam_test.py, utils/mixin.py
Closes https://github.com/coala/corobo/issues/586
Closes https://github.com/coala/corobo/issues/587
=> configuration: Use default configurations

test-requirements.txt
=> test-requirements.txt: Sync

answers/requirements.txt
Closes https://github.com/coala/corobo/issues/593
=> answers/requirements.txt: Remove unused nltk 

.ci/semaphore.docker.sh
Fixes https://github.com/coala/corobo/issues/583
=> ci: Add repository check to semaphore scripts

config.py
Blacklisted user from-somewhere-else as it is the IRC bot.
Closes https://github.com/coala/corobo/issues/336
=> config.py: Blacklist from-somewhere-else user

.editorconfig, .gitignore, .moban.yaml, setup.cfg, test-requirements.txt
=> Add .editorconfig & moban sync

.ci/semaphore.tests.sh
Closes https://github.com/coala/corobo/issues/654
=> semaphore.tests.sh: Use coala master

.gitignore, setup.cfg, test-requirements.txt
Performed a moban sync due to a change in
xdist and pytest versions causing the corobo
repo to fail.
Fixes https://github.com/coala/corobo/issues/660
=> Moban Sync on repository
