coala/corobo

.travis.yml
README.md
test-requirements.txt

Closes https://github.com/coala/corobo/issues/80

.travis.yml: Fail if coverage less than 100

---

.travis.yml

Fixes https://github.com/coala/corobo/issues/85

.travis.yml: Calculate coverage of plugins and not tests

---

plugins/constants.py
plugins/labhub.py
requirements.txt
tests/helper.py
tests/labhub_test.py

Closes https://github.com/coala/corobo/issues/2

gsoc: [please merge :P ] LabHub: Add github plugin with invite feature

---

utils/utils.py

- Install requirements by running pip install in subprocess.
- Make `sync` admin_only command.
Closes https://github.com/coala/corobo/issues/151

utils: Add install requirements command

---

plugins/labhub.py

Eligibility message changed from 'then newcomers' to 'than newcomers'
Fixes https://github.com/coala/corobo/issues/157

labhub: Fix typo then -> than

---

plugins/labhub.py

When issue assignment fails, suggests that user may not be part of coala
org yet.
Closes https://github.com/coala/corobo/issues/181

Enhances issue assign failure message

---

plugins/labhub.py
tests/labhub_test.py

Closes https://github.com/coala/corobo/issues/225

labhub: Maintain a list of invited users

---

plugins/labhub.py

This change makes the GCI related condition of corobo message to appear
in a new line.
Closes https://github.com/coala/corobo/issues/310

labhub.py: Add comma in eligility_conditions

---

plugins/labhub.py
tests/labhub_test.py

This will generate a message that issue is already assigned to you, if both user and assignee are same.
Closes https://github.com/coala/corobo/issues/324

labhub.py: Add reassign message

---

plugins/labhub.py
tests/labhub_test.py

This prepends ^ in the invite command
regex to make sure it is not triggered
from anywhere in the conversation
Fixes https://github.com/coala/corobo/issues/215
Also Fixes https://github.com/coala/corobo/issues/323

labhub.py: Fix invite command regex bug

---

config.py

The Text backend needs the bot admin to start with `@`.
Fixes https://github.com/coala/corobo/issues/393

config.py: Add special case for Text backend

---

plugins/explain.py
tests/explain_test.py

Add ^ and $ to the regex so the command is not triggered
from anywhere in the capture string
Closes https://github.com/coala/corobo/issues/364

explain.py: Recognize beginning and end of string

---

plugins/labhub.py
tests/labhub_test.py

This reverts commit 2a505f2e5dc6c02c39007533eb9c6268cf5ccdf5.

Revert "LabHub: Block gci issue assignments"

---

plugins/labhub.py

This changes the spelling of `create_issut_cmd` to `create_issue_cmd`.
Closes https://github.com/coala/corobo/issues/362

labhub.py: Fix spelling mistake

---

plugins/labhub.py
tests/labhub_test.py

This allows repository names to contain periods when creating
issues, allowing for GitHub pages repos to be used.
Fixes https://github.com/coala/corobo/issues/252

labhub.py: Allow periods in repository names

---

plugins/labhub.py

labhub.py: Changed invite alias 
Changed invite alias from 'invite' to 'welcome'.
Closes https://github.com/coala/corobo/issues/166

labhub.py: Change invite alias

---

utils/utils.py

utils/utils.py: Use bot configuration
Use COBOT_ROOT variable set in config.py
instead of accessing enviroment.
Fixes https://github.com/coala/corobo/issues/384

utils/utils.py: Use bot configuration

---

plugins/labhub.py
tests/labhub_test.py

This will ping the author of a PR when it is marked as WIP through the
`corobo mark wip <issue>` command.
Closes https://github.com/coala/corobo/issues/333

labhub.py: Ping PR author when marking WIP

---

plugins/labhub.py
tests/labhub_test.py

labhub.py: Add "mark pending review" alias
Add "mark pending review" and
"mark pending-review" aliases.
Fixes https://github.com/coala/corobo/issues/335

labhub.py: Add "mark pending review" alias

---

plugins/labhub.py
requirements.txt
tests/labhub_test.py

This will get the author from IGitt as opposed to checking the raw data
from GitHub and GitLab.
Fixes https://github.com/coala/corobo/issues/419

labhub.py: Get author from IGitt

---

requirements.txt

The latest release is causing connection problems
on corobo only.
Fixes https://github.com/coala/corobo/issues/433

requirments.txt: Pin pyopenssl before 17.5.0

---

plugins/git_stats.plug
plugins/git_stats.py
tests/git_stats_test.py

labhub.py: list rebased PRs
Add list mergre-ready PRs command
'pr list \<complete-repo-URL\>'.
Lists open PRs, which don't need
rebase and have 'process/approved'
or 'process/review_pending' labels.
Closes https://github.com/coala/corobo/issues/171

git_stats.py: New plugin

---

config.py

Add ACCESS_CONTROLS for render test command
Closes https://github.com/coala/corobo/issues/359

config.py: Limit render test in test room

---

plugins/labhub.py

This mentions that the medium level and unlabelled issues cannot be
assigned to newcomers and they need to complete the developer
process to get themselves assign such issues.
closes #296

changes to labhub.py :to add an extra message when newcomer tries to assign medium issues

---

config.py
tests/labhub_test.py

config.py: Restrict private issue creation
Don't allow users to
create issues in private conversations
with corobo
Fixes https://github.com/coala/corobo/issues/391

config.py: Restrict private issue creation

---

.coafile

Changes `[commits]` to `[commit]`.
Closes https://github.com/coala/corobo/issues/451

.coafile: Fix a typo

---

plugins/labhub.py
tests/labhub_test.py

Use web_url to get HTML URL instead of API URL.
Add basic tests for the same.
As @meetmangukiya already noted on [gitter](https://gitter.im/coala/corobo?at=5a20549b71ad3f87364d83c4), it's mildly redundant to add tests(since they mock the property being tested)
Closes https://github.com/coala/corobo/issues/426

labhub: Use web_url instead of url

---

plugins/git_stats.plug

Change spelling on line 6 of git_stats.plug file from GitLub to GitLab
fixes <https://github.com/coala/corobo/issues/490>

git_stats.plug: Fix spelling from 'GitLub' to 'GitLab'

---

plugins/labhub.py

labhub: Show 'invite me' as help in `invite_cmd` 
The help command will now show how the invite command can work in two formats, displayed as a single string `'invite ([@]<username> [to <team>]|me)'`. Added a test to verify this as well.
Closes #307 

Closes #307

---

plugins/labhub.py
tests/labhub_test.py

labhub: Change regex pattern for 'invite_cmd'
The original file had regex for `\s*` which matches 0 or more whitespaces which led to matches such as *'invite @userto developers'* since it matched 0 whitespaces between *'@user'* and *'to'*. With `\s+` it matches 1 or more whitespace and hence *'invite @userto developers'* will not be matched. Added a test to verify this as well.
Fixes https://github.com/coala/corobo/issues/512

Closes #512

---

plugins/labhub.py
requirements.txt
tests/labhub_test.py

Update `org.iter_teams` to `org.teams` as per
the new release notes of github3.py v1.0.0

Fix semaphore builds

---

README.md
config.py

Deprecate the use of the environment variable COBOT_PREFIX and
replace it with BOT_PREFIX, issue a warning if COBOT_PREFIX is
still being used.
Closes https://github.com/coala/corobo/issues/370

Deprecate COBOT_PREFIX

---

Dockerfile
README.md
config.py
utils/utils.py

Add backward compatibilty for COBOT_ROOT with a
warning.
Closes https://github.com/coala/corobo/issues/371

Rename COBOT_ROOT to BOT_ROOT

---

plugins/labhub.py
plugins/templates/labhub/errors/not-eligible.jinja2.md
tests/labhub_test.py

Newcomers won't be able to get assigned to
more that one newcomer issue.
Closes https://github.com/coala/corobo/issues/540

[GSoC '18] labhub: assign_cmd newcomer's issue tracker

---

plugins/labhub.py
plugins/templates/labhub/errors/not-eligible.jinja2.md
tests/labhub_test.py

Block assignment of issues labeled as
'initiatives/gci'.
Closes https://github.com/coala/corobo/issues/501

labhub.py: Block gci issue assignment

---

plugins/labhub.py

Removed variable invited_users from class LabHub as it is not used
anywhere.
Closes https://github.com/coala/corobo/issues/557

labhub.py: Remove unused variable

---

tests/labhub_test.py

Default 5 sec timeout was causing unexpected random CI
failure.
Closes https://github.com/coala/corobo/issues/564

labhub_test: Increase timeout to fix random CI failures

---

plugins/labhub.py
tests/labhub_test.py

Redefine excessive usage for the list
of teams.
Closes https://github.com/coala/corobo/issues/575

LabHub: Remove redundant teams list

---

plugins/git_stats.plug
plugins/git_stats.py
tests/corobo_test_case.py
tests/git_stats_test.py

Inheritence was resulting in labhub commands
being triggered twice when used. This creates
dependency on labhub instead of inheritance.
Fixes https://github.com/coala/corobo/issues/441

GitStats: Remove LabHub inheritance

---

plugins/coatils.py

This removes __init__ initializer as the __init__ in this module
only invokes super, which happens anyway if ___init__ is removed
Closes https://github.com/coala/corobo/issues/601

plugins/coatils.py: Remove __init__ constructor

---

plugins/nevermind.py
tests/nevermind_test.py

Change regex pattern so that corobo only apologizes
when "corobo nm" or "corobo nevermind" are used.
Also add unit tests for the same
Fixes https://github.com/coala/corobo/issues/519

nevermind.py: Change regex pattern

---

tests/git_stats_test.py
tests/labhub_test.py
tests/labhub_test_case.py

The role of LabHubTestCase is to do the setUp
necessary for testing a plugin which depends
on LabHub plugin. It adapts the tests for
GitStats plugins to use the LabHubTestCase.
Closes https://github.com/coala/corobo/issues/607

LabHubTestCase: LabHub testing setup 

---

config.py
plugins/constants.py
plugins/labhub.py
tests/answer_test.py
tests/coala_lowercase_c_test.py
tests/coatils_test.py
tests/corobo_test_case.py
tests/deprecate_bot_prefixes_test.py
tests/explain_test.py
tests/ghetto_test.py
tests/isolated_testcase.py
tests/labhub_test.py
tests/lmgtfy_test.py
tests/nevermind_test.py
tests/pitchfork_test.py
tests/searchdocs_test.py
tests/ship_it_test.py
tests/spam_test.py
tests/the_rules_test.py
tests/wolfram_alpha_test.py

`__init__` is executed at load time and
and any issue in the plugin will lead
to it not showing up.
LifeCycle: `__init__`->configured->enable
Adapts to the `DefaultConfigMixin` and
migrated to using configuration templates.
Closes https://github.com/coala/corobo/issues/554
Closes https://github.com/coala/corobo/issues/382

LabHub: Use activate and configuration templates

---

config.py
plugins/answer.py
plugins/wolfram_alpha.plug
plugins/wolfram_alpha.py
setup.cfg
tests/answer_test.py
tests/spam_test.py
tests/wolfram_alpha_test.py
utils/mixin.py

Store the default values in `CONFIG_TEMPLATE` and
then allow a subset of those config variables
overridden in the config.py's `DEFAULT_CONFIG`.
Closes https://github.com/coala/corobo/issues/596

DefaultConfigMixin: Modify implementation

---

.travis.yml
tests/answer_test.py
tests/lmgtfy_test.py
tests/the_rules_test.py
tests/wolfram_alpha_test.py

The default `install:` phase of Travis CI does
`pip install -r requirements.txt`, which was
duplicated by the custom `before_script:` block.

.travis.yml: Install using pip once

---

README.md

This adds an explanation that BOT_ADMINS is a space separated list.
Fixes https://github.com/coala/corobo/issues/367

README.md: Update BOT_ADMINS description

---

config.py

This removes the coala/ prefix from all rooms
and adds rooms mentioned in the wiki.
Closes https://github.com/coala/corobo/issues/412

config.py: Update default channel list

---

plugins/constants.py
tests/searchdocs_test.py

This changes http:// links in constants.py file in plugins folder 
and searchdocs_test.py file in tests folder to https:// links.
Closes [#579](https://github.com/coala/corobo/issues/579)

searchdocs_test: change http links to https

---

config.py

Added this code which if the `BACKEND` is run as `'Zulip'` ROOMS_TO_JOIN is updated accordingly.
I noticed there's not much code for Zulip(a cursory search shows no matches in the repo). So this will probably make someone's life easier down the line when they port the bot.
:sparkles: 
Third time's the charm :crossed_fingers: 
closes #635 

Added 'Zulip' as option for ROOMS_TO_JOIN

---

.gitignore
.moban.yaml
requirements.txt

requirements.txt: Use most recent IGitt version

---

plugins/labhub.py
tests/labhub_test.py

All of the backends do not have `nick` attribute.
Hence an error will be shown whenever nick is empty.
Closes https://github.com/coala/corobo/issues/632

labhub.py: Add error message when nick is empty

---

config.py

Removed `corobo` as default `BOT_PREFIX`
and added a check for empty `BOT_PREFIX`
Closes https://github.com/coala/corobo/issues/365

config.py: Remove corobo as default prefix
